version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: qms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: qms
      POSTGRES_PASSWORD: qms123
      POSTGRES_DB: qms_factory
    ports:
      - '5432:5432'
    volumes:
      - qms_postgres_data:/var/lib/postgresql/data

volumes:
  qms_postgres_data:
